### ISSUE TITLE
nLogin don't let me enter in the server

### ISSUE THREAD

**Issue by Erlandux** [nickuc/OpeNLogin#102]
Hello, i have a Mohist 1.12.2 server and i'm currently using ProtocolLib 4.8.0 and the latest version of nLogin in my server beacause ProtocolLib 5.0.0 and 5.0.1 don't start I don't know why.
Yesterday I was playing on my server with some people and after a normal restart the nLogin just was not more letting me enter my server and all of the other people are not able to join my server too. I don't know why, I tried adding more RAM and more CPU for the server, I tried changing for other versions of ProtocolLib (because the error is betwen ProtocolLib and nLogin) , but nothing worked.
(I opened an Issue in ProtocolLib and they said to open an issue here)

What shows on my console when I trie to join the server:
[13:55:14 INFO]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@5a4505c0.
[13:55:14 ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.RuntimeException: Error occured while instancing generated class.
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
at com.comphenix.protocol.events.PacketContainer.(PacketContainer.java:139)
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
at com.nickuc.antibot.ςβξιααυει.a(:288)
at com.nickuc.antibot.ςβξιααυει.channelRead(:243)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
at com.nickuc.antibot.ΩδΦσωπηοεςβοφΛτ.channelRead(:90)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
at com.nickuc.antibot.ΣΦΦνιγςφ.channelRead(:35)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
... 59 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketHandshakingInSetProtocol
at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_C00Handshake$java_lang_Object.(Unknown Source)
... 64 more
Dump:
Parameters:
io.netty.buffer.UnpooledSlicedByteBuf@16690f6f[
buffer=io.netty.buffer.PooledUnsafeDirectByteBuf@4d7f4bf0
adjustment=1
readerIndex=30
writerIndex=30
markedReaderIndex=0
markedWriterIndex=0
maxCapacity=30
]
manager:
com.comphenix.protocol.injector.PacketFilterManager@783ffcd9[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4f2808e5
packetListeners=[com.comphenix.protocol.async.NullPacketListener@4530533, PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=nLogin, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]]]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@589c63b8
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@72227aa1
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@75fc9908
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7a1cd872
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@7b1ea6a3
reporter=com.comphenix.protocol.ProtocolLib$1@41a6e52a
server=CraftServer{serverName=Mohist,serverVersion=git-Mohist-1.12.2-321,minecraftVersion=1.12.2}
library=ProtocolLib v4.8.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3195811a
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=1
phasePlayingCount=8
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65fa01cb
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@78b15be6
hasRecycleDistance=true
minecraftVersion=(MC: 1.12.2)
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ChannelInjector@5a4505c0[
decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
factory=com.comphenix.protocol.injector.netty.InjectionFactory@74054a3d
player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@4144e92f
updated=
playerName=
playerConnection=
networkManager=net.minecraft.network.NetworkManager@3358f48a
originalChannel=[id: 0xffa8559d, L:/172.18.0.4:25793 - R:/85.138.88.224:53971]
channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@3358f48a, previous=[id: 0xffa8559d, L:/172.18.0.4:25793 - R:/85.138.88.224:53971], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@40c537f3, previousLoaded=true, currentSet=true, forceAccess=true]
packetMarker={}
currentEvent=
finalEvent=
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@45e8a82
vanillaDecoder=net.minecraft.network.NettyPacketDecoder@7aee8900
vanillaEncoder=net.minecraft.network.NettyPacketEncoder@325832c9
finishQueue=[]
channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@65fa01cb
processor=com.comphenix.protocol.injector.NetworkProcessor@2b316abf
injected=true
closed=false
cumulation=UnpooledSlicedByteBuf(ridx: 30, widx: 30, cap: 30/30, unwrapped: PooledUnsafeDirectByteBuf(ridx: 42, widx: 42, cap: 42))
cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@25994050
singleDecode=false
decodeWasNull=false
first=true
decodeState=1
discardAfterReads=16
numReads=0
added=true
]
Version:
ProtocolLib v4.8.0
Java Version:
1.8.0_312
Server:
git-Mohist-1.12.2-321 (MC: 1.12.2)
[13:55:14 WARN]: java.lang.IllegalStateException: Handshake data is null in LOGIN state for com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@4144e92f!
[13:55:14 WARN]: at com.nickuc.login.ξξψγξπιω.a(:61)
[13:55:14 WARN]: at com.nickuc.login.ξξψγξπιω.onPacketReceiving(:87)
[13:55:14 WARN]: at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642)
[13:55:14 WARN]: at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596)
[13:55:14 WARN]: at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48)
[13:55:14 WARN]: at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229)
[13:55:14 WARN]: at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300)
[13:55:14 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[13:55:14 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50)
[13:55:14 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:55:14 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:55:14 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:55:14 WARN]: at java.lang.Thread.run(Thread.java:748)
[13:55:14 INFO]: [nLogin] [ERROR] [Premium] Could not handle incoming packet using ProtocolLib
[13:55:44 INFO]: /85.138.88.224:53971 lost connection: Disconnected

I don't know what to do, anyone can help me?

**Comment by nickuc** [comment]
Hi, @Erlandux!

You need to use ProtocolLib v4.6.0 if you are using Mohist 1.12.

https://github.com/MohistMC/Mohist/issues/2355#issuecomment-1298359242

**Comment by Erlandux** [comment]
I installed the ProtocolLib v4.6.0 and dindn't worked, but I tried ProtocolLib v4.5.1 and it worked, thanks for helping
