### ISSUE TITLE
OpeNLogin doesn't install on Aternos.

### ISSUE THREAD

**Issue by 09ernjke** [nickuc/OpeNLogin#106]
I'm using Arclight software in version 1.16.5, and in the plugins folder, I only have OpenNlogin. When I start the server and log in, I don't see any message, and it doesn't allow me to register. When I try to use any plugin command, it gives me this error:

[28Oct2023 19:44:48.633] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
org.bukkit.command.CommandException: Cannot execute command 'nlogin' in plugin OpeNLogin v1.6.5 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2547) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2397) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.md3aacb2$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]

What can I do? Is there a solution?😵

**Comment by nickuc** [comment]
Hi, @09ernjke 

If possible send here your entire server latest logs
