### ISSUE TITLE
ProtocolLib error on turn off

### ISSUE THREAD

**Issue by KIRUYXAN** [nickuc/OpeNLogin#114]
[00:05:55 ERROR]: [nLogin] [ProtocolLib] Failed to unhook ProtocolLib protocols.
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1633) ~[?:?]
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-32.1.2-jre.jar:?]
at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1400) ~[guava-32.1.2-jre.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.async.AsyncFilterManager.unregisterAsyncHandlers(AsyncFilterManager.java:289) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.async.AsyncFilterManager.unregisterAsyncHandlers(AsyncFilterManager.java:283) ~[ProtocolLib.jar:?]
at com.nickuc.login.υααψψγξΔψεΠαθυκ.J(:125) ~[?:?]
at com.nickuc.login.ΨεηηνμγυΩαγ.H(:92) ~[?:?]
at com.nickuc.login.ιθΣτΔηΓωζξρβ.k(:218) ~[?:?]
at com.nickuc.login.χιςζΓθωφρο.L(:267) ~[?:?]
at com.nickuc.login.γξθσβπΦΨ.L(:77) ~[?:?]
at com.nickuc.login.αχδΦΨςφΣφΣκ.L(:74) ~[?:?]
at com.nickuc.login.ΦνςαΦΣμΩΨΣΦπρ.an(:347) ~[?:?]
at com.nickuc.login.γξθσβπΦΨ.disable(:54) ~[?:?]
at nLogin.jar/com.nickuc.login.loader.platform.BukkitLoader.onDisable(BukkitLoader.java:37) ~[nLogin.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-15-2df432f]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.jar:1.21-15-2df432f]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.jar:1.21-15-2df432f]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:598) ~[paper-1.21.jar:1.21-15-2df432f]
at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:988) ~[paper-1.21.jar:1.21-15-2df432f]
at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:845) ~[paper-1.21.jar:1.21-15-2df432f]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[paper-1.21.jar:1.21-15-2df432f]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-15-2df432f]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by nickuc** [comment]
Hello, @KIRUYXAN 

This has to do with the recent updates to the ProtocolLib injector. You can ignore it for now.

I'm working on an update to remove the dependency on ProtocolLib. News will be announced in the Discord group.

**Comment by KIRUYXAN** [comment]
OK, thank you
