### ISSUE TITLE
Log-in error

### ISSUE THREAD

**Issue by victordosanjos** [nickuc/OpeNLogin#31]
I'm getting this error after connecting to my server

`[05:57:28 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
[05:57:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[05:57:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[05:57:28 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[05:57:28 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[05:57:28 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[05:57:28 WARN]:        at com.nickuc.openlogin.bukkit.reflection.ReflectionUtils.getNMS(ReflectionUtils.java:22)
[05:57:28 WARN]:        at com.nickuc.openlogin.bukkit.reflection.packets.Packet.<clinit>(Packet.java:30)
[05:57:28 WARN]:        at com.nickuc.openlogin.bukkit.listeners.PlayerJoinListeners.onPlayerJoin(PlayerJoinListeners.java:64)
[05:57:28 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source)
[05:57:28 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[05:57:28 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:57:28 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:57:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[05:57:28 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:357)
[05:57:28 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:299)
[05:57:28 WARN]:        at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:308)
[05:57:28 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:399)
[05:57:28 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:196)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1576)
[05:57:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[05:57:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[05:57:28 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.IChatBaseComponent
[05:57:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[05:57:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[05:57:28 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[05:57:28 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[05:57:28 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[05:57:28 WARN]:        at com.nickuc.openlogin.bukkit.reflection.ReflectionUtils.getNMS(ReflectionUtils.java:22)
[05:57:28 WARN]:        at com.nickuc.openlogin.bukkit.reflection.packets.TitleAPI.<clinit>(TitleAPI.java:59)
[05:57:28 WARN]:        at com.nickuc.openlogin.bukkit.listeners.PlayerJoinListeners.onPlayerJoin(PlayerJoinListeners.java:64)
[05:57:28 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source)
[05:57:28 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[05:57:28 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:57:28 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:57:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[05:57:28 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:357)
[05:57:28 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:299)
[05:57:28 WARN]:        at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:308)
[05:57:28 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:399)
[05:57:28 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:196)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1576)
[05:57:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[05:57:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[05:57:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by nickuc** [comment]
Hi, @victordosanjos!

Seems to be a problem with the new version 1.17. I'll fix it when it's available.

**Comment by nickuc** [comment]
Fixed in 8c49f65a117366296f2c4d465ffa4322cd88b9bc
