### ISSUE TITLE
NoSuchMethodException: java.util.Arrays$ArrayList.<init>()

### ISSUE THREAD

**Issue by xotrikspl** [nickuc/OpeNLogin#34]
[07:07:34 WARN]: java.lang.NoSuchMethodException: java.util.Arrays$ArrayList.<init>()
[07:07:34 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
[07:07:34 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2151)
[07:07:34 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[07:07:34 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[07:07:34 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[07:07:34 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[07:07:34 WARN]:        at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[07:07:34 WARN]:        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[07:07:34 WARN]:        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[07:07:34 WARN]:        at com.nickuc.login.λΦλΦΨΛπΩΛΩ.i(ä⹪⺚⺋⹗⺠⹴⹾⺡⹜⹛⹵⹽⺢⺇⹶⹿⹨⺨⺈⺚⹻⺈⺰⺲⺧⺵⺀⺓⹴⹷⺔⺭⺸⺉⺚⺼⺰⹹⺩⺗⹾⹺⺮⺜⺖⺜⺻⻄⺟⺵⺍⺭⺣⻎⺕⺖ödTBHZöü:100)
[07:07:34 WARN]:        at com.nickuc.login.εθοΦςλΣψυχξ.i(äöKNDBZöölCYWOö琳珸琁琯琘琜琪珻琠琩琮琠球瑀珷琣琄琹琠琗瑇琬琟琻琪琉琉琪琑瑉瑉琲琗琐琴瑏琷琲琕瑞瑘琼琶琿琹瑏瑄瑐瑢瑆瑕瑘琨琤瑬瑈琧瑧瑠瑓瑝琰瑖瑧瑟瑑瑫瑌瑴瑺瑳瑑琽瑌瑸瑢瑯瑤瑁瑑璇瑘璇瑨璄璈瑊瑢瑩瑤瑊瑪璉璁瑥瑪璒璔瑢璏瑪璆璇璐瑞璙瑠瑡瑮瑷璛璐瑝瑼璢璟璅瑴瑱瑲öDNMKCöᒭᓵᓕᓈᓜᓹᓦᓛᓛᓓᓠᓷᒼᒽᓞᓃᓥᓤᓾᔃᔁᓠᓦᓊᓘᓥᓾᓮᓫᔎᔎᔁᔏᔋᔔᔘᔚᓕᔒᓛᔑᔠᔠᔘ���ᔐᔓᔣᔢᔣᓛᔅᔩᔛᓥᔤᔰᓧᔢᓽᓽᔄᔢᓴᓭᔯᔓᔉᔻᔴᔰᔙᔓᔌᔔᕃᔔᔸᕅᔟᔇᔇᕁᔳᔋᕍᔢᔎᕊᔼᕉᔉᔑᔟᕇᕊᔫᔕᕙᔧᔒᕛᕗᔰᔺᕌᔭᔦöjOxlköü:79)
[07:07:34 WARN]:        at com.nickuc.login.σΛδμΨβΣωηζ.a(äTywEsiTwARugLqAgGQi5VYKRn7eR9mPqDeQIrPoT8cpq3Al0K565vja/xVA=15öjOTKlö석섎섉샸섡설섏샭선섰섒섖섇섚섂샺샲섦섴셀샽섰셀섾섑샿샸섖섆성섔섧섩섟섞셀셍셒셆섑섳셄셌섿섴셕션섷섭셊석셐섯셟선성섵섛셕섡셖섳셇셕섦섬셤셆셇셫섰셴셋섾셂섭셖셏셦셸셹셊섰셽셬셫셝셰셁셴셅셏셁솀셤셶셈솆셡셮솂셝셬솇솎셐셷솎솓솖셓솆셴셏셾솕솒솏솏셭셞셰셥셲셺솟솒솁솤셟솈셻솦솰셯솪셴솝속솈솇솹솪솴솭솇솦솕솘솲솀송솬솽솦솼셿솟솶솪솅솝쇅솆솫솬쇒솒쇅솭쇌쇉솸솒솺솗솶쇘솫쇊쇠솩솦솧öJYAbZö閑镠閉长长镩閎镥閊镦镤镪长镮镮閐閁閤镡镽镻閔閈閆镧镴镞镹閆閛閯閭閑镩閡閒镭长镱閮閸閭閄镺閩閝閖閴閊門閁闀閹閗閳閉閔閶閘閥閜閙闈閛闊閥閪閝閿閬閶闈閹閯閨閮關閹闐闐闂闏閟閥閦閰闡閥閶闄闅閤闥闝闪閨闤閫问闇閿闣闕闄闺闋闲闩闟闇阁闏闯闷闢���阆闸闢阂阈闢闷闋闻阆闠门闛闭闑门阐闷阇闋闹阊阙闹阎闘闚闪队闢闤阏阘阦阡阠阧阝阋闦阤阄阉阒阏闳阞闯闵阃阮阁阳阖阜阁öUDyaRöü:291)
[07:07:34 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source)
[07:07:34 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[07:07:34 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[07:07:34 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:07:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:598)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1986)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:713)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:193)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1597)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
[07:07:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[07:07:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by xotrikspl** [comment]
plugin - nlogin
how? quit the game

**Comment by nickuc** [comment]
Hi, @xotrikspl! 

This error message is being sent by ProtocolLib. 
This stack trace has been removed in this commit: https://github.com/dmulloy2/ProtocolLib/commit/4c0c18d7c61b0471cfbfd7a0017a170dd2264e50

To hide it, use the latest plugin build:
https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by xotrikspl** [comment]
> 
> 
> Hi, @xotrikspl!
> 
> This error message is being sent by ProtocolLib.
> This stack trace has been removed in this commit: [dmulloy2/ProtocolLib@4c0c18d](https://github.com/dmulloy2/ProtocolLib/commit/4c0c18d7c61b0471cfbfd7a0017a170dd2264e50)
> 
> To hide it, use the latest plugin build:
> https://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/
