### ISSUE TITLE
citizens error with nlogin 

### ISSUE THREAD

**Issue by shiref11** [nickuc/OpeNLogin#74]
i got this when placing citizens.jar and restarting the server 

[14:47:52 ERROR]: Could not pass event EntityRegainHealthEvent to nLogin v10.1.7
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
        at com.nickuc.login.ρααΨξφζκξπψοΩ.b(:21) ~[?:?]
        at com.nickuc.login.ΓφτνρνυρΣ.a(:69) ~[?:?]
        at com.nickuc.login.ΓφτνρνυρΣ.a(:44) ~[?:?]
        at com.nickuc.login.ΓφτνρνυρΣ.a(:32) ~[?:?]
        at com.nickuc.login.ΠισλζρσΣκγηαιολ.a(:56) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-135]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.heal(LivingEntity.java:1268) ~[?:?]
        at net.minecraft.world.food.FoodData.tick(FoodData.java:87) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:285) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:677) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:365) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:579) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1584) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-135]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
        ... 23 more
[14:47:55 INFO]: [nLogin] The user 4ime has successfully logged in.
[14:48:02 INFO]: 4ime issued server command: /npc
[14:48:02 ERROR]: null

**Comment by nickuc** [comment]
Hi, @shiref11!

It is a problem with Citizens bootstrap.

Try troubleshooting its initialization first.
