### ISSUE TITLE
Falling Error

### ISSUE THREAD

**Issue by Jallepro10** [nickuc/OpeNLogin#87]
[22:44:42 ERROR]: Could not pass event EntityDamageByEntityEvent to OpeNLogin v1.6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-067a583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-067a583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:109) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:555) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:468) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:587) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityLiving.d(EntityLiving.java:1059) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityHuman.d(EntityHuman.java:844) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:698) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:785) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:470) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityFishingHook.h(EntityFishingHook.java:189) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1670) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1637) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1485) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:511) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:764) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:641) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:547) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-067a583]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.entity.Entity.getName()'
        at com.nickuc.openlogin.bukkit.listener.PlayerGeneralListeners.onEntityDamageByEntity(PlayerGeneralListeners.java:129) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[server.jar:git-PaperSpigot-067a583]
        ... 22 more
[22:44:42 ERROR]: Could not pass event EntityDamageByEntityEvent to OpeNLogin v1.6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-067a583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-067a583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:109) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:555) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:468) [server.jar:git-PaperSpigot-067a583]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:587) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityLiving.d(EntityLiving.java:1059) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityHuman.d(EntityHuman.java:844) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:698) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:785) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:470) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.EntityFishingHook.h(EntityFishingHook.java:189) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1670) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1637) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1485) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:511) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:764) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:641) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:547) [server.jar:git-PaperSpigot-067a583]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-067a583]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.entity.Entity.getName()'
        at com.nickuc.openlogin.bukkit.listener.PlayerGeneralListeners.onEntityDamageEvent(PlayerGeneralListeners.java:85) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[server.jar:git-PaperSpigot-067a583]
        ... 22 more

IDK why

**Comment by nickuc** [comment]
Solved in https://github.com/nickuc/OpeNLogin/commit/1ce258b1149a3508b70611fc124735952bdaf17b, download the v1.6.3 version
